### ISSUE TITLE
Non-static method MyPackage\MyPackage::multiply() should not be called statically

### ISSUE THREAD

**Issue by vadiasov** [lasselehtinen/MyPackage#1]
`public function index()
    {
        $result = MyPackage::multiply(5, 8);
    
        var_dump($result);
        die();
        return view('home');
    }`

Non-static method MyPackage\MyPackage::multiply() should not be called statically.

**Comment by lasselehtinen** [comment]
I guess you are including the class directly? So please add the service provider MyPackageServiceProvider to config/app.php and try again.

**Comment by vadiasov** [comment]
Yes, of course.

use Vadiasov\MyPackage\MyPackageFacade;
public function index()
    {
        $result = MyPackageFacade::multiply(5, 8);    
        var_dump($result);
        die();
        return view('home');
    }

Sorry to disturb you.

**Comment by lasselehtinen** [comment]
I realised my mistake, including the facade is of course the wrong way. Please check the updated comment.

**Comment by vadiasov** [comment]
Without facade it's working with backslash:
$result = \MyPackage::multiply(5, 8);
